Yuto/styling create project page
youngeek-0410/hacku-kosen-2022-frontend pull request #17
Opened 2022-12-14 02:57 UTC by myuto7

2022-12-15 00:27 UTC, shoma3571 requested changes
細かいCSSまではレビューできてないけど、`svh`だとSafariにしか効かないから`vh`に変更してほしい。
Safari first で対応するよりはChrome first で対応したほうがいいかなって考えてるんだけどどうかな？

https://coliss.com/articles/build-websites/operation/css/large-small-dynamic-viewports.html

対応策としては、100vhに変更してからボタンの下とのmarginを大きくすることで、Safariでもボタンを表示できるようにするとかはありかな〜って思う

2022-12-15 00:27 UTC, shoma3571 commented on src/projects/NewProjectPage.tsx
> +  minHeight: "100svh",
`minHeight: "100vh"`

2022-12-15 06:07 UTC, shoma3571 approved these changes
LGTM

2022-12-15 06:07 UTC, merged

2022-12-15 08:26 UTC, igsr5 commented
https://zenn.dev/moneyforward/articles/svh-dvh-lvh-for-all-browser

最近googleもsvh, ...etc 対応してくれてるので一応共有(上の記事バズってた)

2022-12-16 00:00 UTC, shoma3571 commented
これ僕のノートPCのChromeが古かったからsvh対応してなかったんだと思う。申し訳ない